---

# hosts reference:
#[ucp-primary] ucp-manager1
#[ucp-replica] ucp-manager2 ucp-manager3
#[ucp-worker]  ucp-node1 ucp-node2
#[dtr-primary] ucp-dtr1
#[dtr-replica] ucp-dtr2 ucp-dtr3

- hosts: all
  roles:
  - ntp
  - pre-deploy
  - docker-ee-install

- hosts: ucp-primary
  roles:
    - docker-ucp-primary

- hosts: ucp-replica
  serial: 1 # join replicas one at a time
  roles:
    - docker-ucp-replica

- hosts: ucp-worker
  roles:
    - docker-ucp-worker

- hosts: dtr-primary
  roles:
    - docker-dtr-primary

- hosts: dtr-replica
  serial: 1 # join replicas one at a time
  roles:
    - docker-dtr-replica

# Note: better to install DTR primary from UCP manager node
- hosts: ucp-primary
  roles:
    - docker-dtr-install

- hosts: dtr-replica
  serial: 1 # join replicas one at a time
  roles:
    - docker-dtr-add-replicas

