---

- name: "Add license file"
  copy:
    src: "docker_subscription.lic"
    dest: /tmp

- debug:
   msg: "UCP Primary Install Params: Host: fqdn: {{ fqdn }} has internal ip: {{ ansible_default_ipv4['address'] }} and lb san: {{ ucp_external_fqdn }}"

- name: "Creating script to pull docker ucp images"
  template: 
    src: pull-ucp-images.sh.j2
    dest: /root/pull-ucp-images.sh
    owner: root
    group: root
    mode: 0755

- name: "Pulling docker ucp images to speed up ucp install.."
  shell: sh -x /root/pull-ucp-images.sh > /root/pull-ucp-images.log 2>&1
  args:
    executable: /bin/bash
    chdir: /root
    creates: /root/pull-ucp-images.log

- name: "Install primary UCP controller"
  # Note: when /root/ucp-primary-install.log exists the command will not rerun
  shell: /bin/docker run --rm --name ucp -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/docker_subscription.lic:/docker_subscription.lic    docker/ucp:{{ ucp_version|quote }} install --admin-username admin --admin-password {{ ucp_admin_password|quote }} --host-address {{ ansible_default_ipv4['address']|quote }} --san {{ fqdn|quote }} --san {{ ucp_external_fqdn|quote }} --san {{ dtr_external_fqdn|quote }} 2>&1 | /bin/tee -a /root/ucp-primary-install.log
  args:
    executable: /bin/bash
    chdir: /root
    creates: /root/ucp-primary-install.log

